PALABRAS_CLAVE_ENO = [
    #NOTIFICACION INMEDIATA
    "botulismo",
    "carbunco", "antrax", "ántrax", "bacteridiano",
    "chagas aguda", "chagas",
    "chikungunya",
    "colera", "cólera",
    "dengue",
    "difteria",
    "fiebre amarilla",
    "hanta", "hantavirus",
    "haemophilus", "influenzae",
    "irag", "inusitada",
    "leptospirosis",
    "malaria",
    "meningitis bacteriana", "meningococo", "neisseria", "meningitidis",
    "fiebre hemorragica", "hemorrágica", "ebola", "ébola", "marburg", "lassa",
    "peste", "plaga",
    "paralisis flacida", "parálisis flácida", "polio", "poliomielitis",
    "rabia",
    "rubeola", "rubéola", "sindrome rubeola congenito",
    "sarampion", "sarampión",
    "triquinosis",
    "nilo occidental",
    "zika",

    #NOTIFICACIÓN DIARIA
    "brucelosis",
    "cisticercosis",
    "creutzfeldt", "jakob", "ecj",
    "coqueluche", "tos ferina", "tos convulsa",
    "tifoidea", "paratifoidea",
    "fiebre q",
    "hepatitis",
    "hidatidosis", "equinococosis",
    "gonorrea", "gonococo", "gonocócica", "gonococcica",
    "leishmaniasis",
    "lepra", "hansen",
    "listeriosis", "listeria",
    "parotiditis", "paperas",
    "psitacosis",
    "rickettsiosis",
    "sifilis", "sífilis",
    "shu", "hemolitico uremico", "hemolítico urémico",
    "neumococo", "pneumoniae", "streptococcus pneumoniae",
    "tetanos", "tétanos",
    "tuberculosis", "tbc", "bacilo de koch", "bk",
    "vih", "inmunodeficiencia",

    # OTRAS VIGILANCIAS Y BROTES
    "covid", "sars", "coronavirus", 
    "influenza", 
    "escabiosis", "sarna", 
    "varicela", "peste cristal",
    "viruela simica", "viruela del mono",
    "plaguicida", "intoxicacion"
]