DIAGNOSTICOS_RESPIRATORIOS = {
    "IRA ALTA": [
        "amigdalitis",
        "faringitis",
        "laringitis",
        "pansinusitis",
        "rinitis alergicas",
        "rinitis cronicas",
        "rinofaringitis",
        "sinusitis",
    ],
    "IRA BAJA": [
        "asma",
        "asma exacerbada",
        "bronconeumonia",
        "bronquiectasia",
        "bronquiolitis",
        "bronquitis aguda",
        "bronquitis cronica",
        "edema pulmonar",
        "enfermedad pulmonar intersticial",
        "enfermedad pulmonar obstructiva cronica",
        "enfermedad pulmonar obstructiva cronica exacerbada",
        "fibrosis",
        "insuficiencia respiratoria aguda",
        "neumoconiosis",
        "neumonia",
        "neumonia bacteriana",
        "neumonia viral",
        "neumonitis",
        "obstructiva",
        "sindrome bronquial",
        "sindrome bronquial obstructivo",
        "sindrome bronquial obstructivo recurrente  o recidivante",
        "tuberculosis",
    ],
    "OTRAS": [
        "covid",
        "disnea",
        "embolia pulmonar",
        "hemoptisis",
        "hipoxia",
        "infección aguda de vias respiratorias inferiores",
        "infección aguda de vias respiratorias superiores",
        "influenza",
        "otitis externa",
        "otitis media",
        "otras causas respiratorias",
        "tumor maligno de los bronquios o del pulmon",
    ]
}